# Generated by Django 5.2.4 on 2025-08-14 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('auto_play', models.BooleanField(default=False)),
                ('animation', models.CharField(max_length=255)),
                ('indicators', models.BooleanField(default=False)),
                ('timeout', models.IntegerField()),
                ('nav_buttons_always_visible', models.BooleanField(default=False)),
                ('cycle_navigation', models.BooleanField(default=False)),
                ('index_banner', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order_number', models.IntegerField()),
                ('duration', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='banners.banner')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteImages.siteimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
