# Generated by Django 5.2.4 on 2025-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holyday',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
