# Generated by Django 5.2.4 on 2025-07-14 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0002_alter_holyday_end_date_alter_holyday_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holyday',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
