# Generated by Django 5.2.4 on 2025-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0003_alter_holyday_end_date_alter_holyday_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holydaytranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
