# Generated by Django 5.2.4 on 2025-07-14 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0004_alter_holydaytranslation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holydayuser',
            name='holyday',
        ),
        migrations.RemoveField(
            model_name='holydayuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='holyday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='holyday',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='holyday',
            name='leave_reasons',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holyday',
            name='locale',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='holyday',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='holyday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holydays', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holyday',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HolydayTranslation',
        ),
        migrations.DeleteModel(
            name='HolydayUser',
        ),
    ]
