# Generated by Django 5.2.4 on 2025-07-29 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0005_remove_holydayuser_holyday_remove_holydayuser_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateHolyday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekendOption', models.BooleanField(null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='holyday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holyday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
