# Generated by Django 5.2.4 on 2025-08-06 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0006_calculateholyday_holyday_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holyday',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='holyday',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
