# Generated by Django 5.2.4 on 2025-08-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0008_historicalholyday'),
        ('solds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalholyday',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='holyday',
            name='locale',
        ),
        migrations.AddField(
            model_name='historicalholyday',
            name='sold',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solds.sold'),
        ),
        migrations.AddField(
            model_name='historicalholyday',
            name='type',
            field=models.CharField(choices=[('annual_leave', 'Congé annuelle'), ('special_leave', 'Congé exceptionnel')], default='annual_leave', max_length=50),
        ),
        migrations.AddField(
            model_name='holyday',
            name='sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holydays', to='solds.sold'),
        ),
        migrations.AddField(
            model_name='holyday',
            name='type',
            field=models.CharField(choices=[('annual_leave', 'Congé annuelle'), ('special_leave', 'Congé exceptionnel')], default='annual_leave', max_length=50),
        ),
    ]
