# Generated by Django 5.2.4 on 2025-08-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holydays', '0009_remove_historicalholyday_locale_and_more'),
        ('solds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holyday',
            name='sold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holydays', to='solds.sold'),
            preserve_default=False,
        ),
    ]
