# Generated by Django 5.2.4 on 2025-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
