# Generated by Django 5.2.4 on 2025-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permissiontranslation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='beginning_hour',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
