# Generated by Django 5.2.4 on 2025-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_alter_permission_beginning_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontranslation',
            name='locale',
            field=models.CharField(default='fr', max_length=255),
        ),
    ]
