# Generated by Django 5.2.4 on 2025-07-13 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_permissiontranslation_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissiontranslation',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='permissions_translations', to='permissions.permission'),
        ),
    ]
