# Generated by Django 5.2.4 on 2025-07-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_permission_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='permission',
            name='locale',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='permission',
            name='nature',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='beginning_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PermissionTranslation',
        ),
    ]
