# Generated by Django 5.2.4 on 2025-07-15 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_remove_permission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
