# Generated by Django 5.2.4 on 2025-07-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_permission_created_at_permission_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='beginning_hour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
